# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/fly1057/桌面/PSS_PyQt5/PSSSettingSoftware.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 733)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        Dialog.setSizeGripEnabled(False)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(600, 260, 591, 471))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DashDotDotLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(20)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(82)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(22)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 164, 179))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_AutoCalculateAndPlot = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_AutoCalculateAndPlot.setFont(font)
        self.pushButton_AutoCalculateAndPlot.setObjectName("pushButton_AutoCalculateAndPlot")
        self.verticalLayout_2.addWidget(self.pushButton_AutoCalculateAndPlot)
        self.pushButton_ManualCalculateAndPlot = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ManualCalculateAndPlot.setFont(font)
        self.pushButton_ManualCalculateAndPlot.setObjectName("pushButton_ManualCalculateAndPlot")
        self.verticalLayout_2.addWidget(self.pushButton_ManualCalculateAndPlot)
        self.pushButton_ReadCSV = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ReadCSV.setFont(font)
        self.pushButton_ReadCSV.setObjectName("pushButton_ReadCSV")
        self.verticalLayout_2.addWidget(self.pushButton_ReadCSV)
        self.pushButton_SaveCSV = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_SaveCSV.setFont(font)
        self.pushButton_SaveCSV.setObjectName("pushButton_SaveCSV")
        self.verticalLayout_2.addWidget(self.pushButton_SaveCSV)
        self.pushButton_Reset = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Reset.setFont(font)
        self.pushButton_Reset.setObjectName("pushButton_Reset")
        self.verticalLayout_2.addWidget(self.pushButton_Reset)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 190, 101, 101))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_PSS1 = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_PSS1.setFont(font)
        self.radioButton_PSS1.setObjectName("radioButton_PSS1")
        self.verticalLayout_3.addWidget(self.radioButton_PSS1)
        self.radioButton_PSS2A = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_PSS2A.setFont(font)
        self.radioButton_PSS2A.setObjectName("radioButton_PSS2A")
        self.verticalLayout_3.addWidget(self.radioButton_PSS2A)
        self.radioButton_PSS2B = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_PSS2B.setFont(font)
        self.radioButton_PSS2B.setChecked(True)
        self.radioButton_PSS2B.setObjectName("radioButton_PSS2B")
        self.verticalLayout_3.addWidget(self.radioButton_PSS2B)
        self.tabWidget_TjCalculation = QtWidgets.QTabWidget(Dialog)
        self.tabWidget_TjCalculation.setGeometry(QtCore.QRect(600, 10, 591, 251))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget_TjCalculation.setFont(font)
        self.tabWidget_TjCalculation.setObjectName("tabWidget_TjCalculation")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 541, 161))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 151, 130))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_5 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_9.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_9.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_9.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_9.addWidget(self.label_32)
        self.formLayout_5.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_9)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.LineEdit_GD2_TurbineHighPressureMass = QtWidgets.QLineEdit(self.layoutWidget)
        self.LineEdit_GD2_TurbineHighPressureMass.setObjectName("LineEdit_GD2_TurbineHighPressureMass")
        self.verticalLayout_7.addWidget(self.LineEdit_GD2_TurbineHighPressureMass)
        self.LineEdit_GD2_TurbineMiddlePressureMass = QtWidgets.QLineEdit(self.layoutWidget)
        self.LineEdit_GD2_TurbineMiddlePressureMass.setObjectName("LineEdit_GD2_TurbineMiddlePressureMass")
        self.verticalLayout_7.addWidget(self.LineEdit_GD2_TurbineMiddlePressureMass)
        self.LineEdit_GD2_TurbineLowPressureMass = QtWidgets.QLineEdit(self.layoutWidget)
        self.LineEdit_GD2_TurbineLowPressureMass.setObjectName("LineEdit_GD2_TurbineLowPressureMass")
        self.verticalLayout_7.addWidget(self.LineEdit_GD2_TurbineLowPressureMass)
        self.LineEdit_GD2_GeneratorMass = QtWidgets.QLineEdit(self.layoutWidget)
        self.LineEdit_GD2_GeneratorMass.setObjectName("LineEdit_GD2_GeneratorMass")
        self.verticalLayout_7.addWidget(self.LineEdit_GD2_GeneratorMass)
        self.formLayout_5.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_7)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(190, 30, 151, 142))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.formLayout_6 = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_10.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_10.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_10.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_10.addWidget(self.label_36)
        self.formLayout_6.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.LineEdit_GR2_TurbineHighPressureMass = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.LineEdit_GR2_TurbineHighPressureMass.setObjectName("LineEdit_GR2_TurbineHighPressureMass")
        self.verticalLayout_11.addWidget(self.LineEdit_GR2_TurbineHighPressureMass)
        self.LineEdit_GR2_TurbineMiddlePressureMass = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.LineEdit_GR2_TurbineMiddlePressureMass.setObjectName("LineEdit_GR2_TurbineMiddlePressureMass")
        self.verticalLayout_11.addWidget(self.LineEdit_GR2_TurbineMiddlePressureMass)
        self.LineEdit_GR2_TurbineLowPressureMass = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.LineEdit_GR2_TurbineLowPressureMass.setObjectName("LineEdit_GR2_TurbineLowPressureMass")
        self.verticalLayout_11.addWidget(self.LineEdit_GR2_TurbineLowPressureMass)
        self.LineEdit_GR2_GeneratorMass = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.LineEdit_GR2_GeneratorMass.setObjectName("LineEdit_GR2_GeneratorMass")
        self.verticalLayout_11.addWidget(self.LineEdit_GR2_GeneratorMass)
        self.formLayout_6.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_11)
        self.label_37 = QtWidgets.QLabel(self.groupBox_4)
        self.label_37.setGeometry(QtCore.QRect(360, 40, 68, 24))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_4)
        self.label_38.setGeometry(QtCore.QRect(360, 70, 91, 24))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox_4)
        self.label_39.setGeometry(QtCore.QRect(360, 100, 68, 24))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.LineEdit_Sn = QtWidgets.QLineEdit(self.groupBox_4)
        self.LineEdit_Sn.setGeometry(QtCore.QRect(450, 40, 71, 24))
        self.LineEdit_Sn.setObjectName("LineEdit_Sn")
        self.LineEdit_RotorSpeed = QtWidgets.QLineEdit(self.groupBox_4)
        self.LineEdit_RotorSpeed.setGeometry(QtCore.QRect(450, 100, 71, 24))
        self.LineEdit_RotorSpeed.setObjectName("LineEdit_RotorSpeed")
        self.LineEdit_GD2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.LineEdit_GD2.setGeometry(QtCore.QRect(450, 70, 71, 24))
        self.LineEdit_GD2.setMaxLength(6)
        self.LineEdit_GD2.setObjectName("LineEdit_GD2")
        self.radioButton_GR2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_GR2.setGeometry(QtCore.QRect(190, 0, 141, 22))
        self.radioButton_GR2.setObjectName("radioButton_GR2")
        self.radioButton_GD2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_GD2.setGeometry(QtCore.QRect(10, 0, 131, 22))
        self.radioButton_GD2.setChecked(True)
        self.radioButton_GD2.setObjectName("radioButton_GD2")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 180, 391, 34))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_TjCalculate = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_TjCalculate.setObjectName("pushButton_TjCalculate")
        self.horizontalLayout.addWidget(self.pushButton_TjCalculate)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout.addWidget(self.label_28)
        self.LineEdit_Tj = QtWidgets.QLineEdit(self.layoutWidget1)
        self.LineEdit_Tj.setMaxLength(30)
        self.LineEdit_Tj.setObjectName("LineEdit_Tj")
        self.horizontalLayout.addWidget(self.LineEdit_Tj)
        self.tabWidget_TjCalculation.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_PSSSettingValue = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_PSSSettingValue.setGeometry(QtCore.QRect(180, 40, 113, 20))
        self.lineEdit_PSSSettingValue.setObjectName("lineEdit_PSSSettingValue")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(30, 40, 131, 21))
        self.label_11.setObjectName("label_11")
        self.Slider_PSSSettingValue = QtWidgets.QSlider(self.tab_2)
        self.Slider_PSSSettingValue.setGeometry(QtCore.QRect(30, 110, 401, 16))
        self.Slider_PSSSettingValue.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Slider_PSSSettingValue.setMinimum(-130)
        self.Slider_PSSSettingValue.setMaximum(-60)
        self.Slider_PSSSettingValue.setSingleStep(5)
        self.Slider_PSSSettingValue.setPageStep(1)
        self.Slider_PSSSettingValue.setProperty("value", -90)
        self.Slider_PSSSettingValue.setSliderPosition(-90)
        self.Slider_PSSSettingValue.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_PSSSettingValue.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_PSSSettingValue.setTickInterval(5)
        self.Slider_PSSSettingValue.setObjectName("Slider_PSSSettingValue")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 140, 441, 18))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_2.addWidget(self.label_17)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_2.addWidget(self.label_16)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_2.addWidget(self.label_15)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_2.addWidget(self.label_18)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_2.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_2.addWidget(self.label_41)
        self.tabWidget_TjCalculation.addTab(self.tab_2, "")
        self.layoutWidget3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(202, 12, 175, 295))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget3)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.LineEdit_Ks1 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.LineEdit_Ks1.setText("")
        self.LineEdit_Ks1.setMaxLength(11)
        self.LineEdit_Ks1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LineEdit_Ks1.setObjectName("LineEdit_Ks1")
        self.verticalLayout_6.addWidget(self.LineEdit_Ks1)
        self.LineEdit_Ks2 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.LineEdit_Ks2.setMaxLength(11)
        self.LineEdit_Ks2.setObjectName("LineEdit_Ks2")
        self.verticalLayout_6.addWidget(self.LineEdit_Ks2, 0, QtCore.Qt.AlignLeft)
        self.LineEdit_Ks3 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.LineEdit_Ks3.setMaxLength(11)
        self.LineEdit_Ks3.setObjectName("LineEdit_Ks3")
        self.verticalLayout_6.addWidget(self.LineEdit_Ks3)
        self.LineEdit_T1 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.LineEdit_T1.setMaxLength(11)
        self.LineEdit_T1.setObjectName("LineEdit_T1")
        self.verticalLayout_6.addWidget(self.LineEdit_T1)
        self.LineEdit_T2 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.LineEdit_T2.setMaxLength(11)
        self.LineEdit_T2.setObjectName("LineEdit_T2")
        self.verticalLayout_6.addWidget(self.LineEdit_T2)
        self.LineEdit_T3 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.LineEdit_T3.setMaxLength(11)
        self.LineEdit_T3.setObjectName("LineEdit_T3")
        self.verticalLayout_6.addWidget(self.LineEdit_T3)
        self.LineEdit_T4 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.LineEdit_T4.setMaxLength(11)
        self.LineEdit_T4.setObjectName("LineEdit_T4")
        self.verticalLayout_6.addWidget(self.LineEdit_T4)
        self.LineEdit_T5 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.LineEdit_T5.setMaxLength(11)
        self.LineEdit_T5.setObjectName("LineEdit_T5")
        self.verticalLayout_6.addWidget(self.LineEdit_T5)
        self.LineEdit_T6 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.LineEdit_T6.setMaxLength(11)
        self.LineEdit_T6.setObjectName("LineEdit_T6")
        self.verticalLayout_6.addWidget(self.LineEdit_T6)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_6)
        self.layoutWidget4 = QtWidgets.QWidget(Dialog)
        self.layoutWidget4.setGeometry(QtCore.QRect(412, 13, 175, 295))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget4)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_4.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_4.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_4.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_4.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_4.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_4.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_4.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_4.addWidget(self.label_27)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_4)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.LineEdit_T7 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.LineEdit_T7.setMaxLength(11)
        self.LineEdit_T7.setObjectName("LineEdit_T7")
        self.verticalLayout_8.addWidget(self.LineEdit_T7)
        self.LineEdit_T8 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.LineEdit_T8.setMaxLength(11)
        self.LineEdit_T8.setObjectName("LineEdit_T8")
        self.verticalLayout_8.addWidget(self.LineEdit_T8)
        self.LineEdit_T9 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.LineEdit_T9.setMaxLength(11)
        self.LineEdit_T9.setObjectName("LineEdit_T9")
        self.verticalLayout_8.addWidget(self.LineEdit_T9)
        self.LineEdit_TW1 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.LineEdit_TW1.setMaxLength(11)
        self.LineEdit_TW1.setObjectName("LineEdit_TW1")
        self.verticalLayout_8.addWidget(self.LineEdit_TW1)
        self.LineEdit_TW2 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.LineEdit_TW2.setMaxLength(11)
        self.LineEdit_TW2.setObjectName("LineEdit_TW2")
        self.verticalLayout_8.addWidget(self.LineEdit_TW2)
        self.LineEdit_TW3 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.LineEdit_TW3.setMaxLength(11)
        self.LineEdit_TW3.setObjectName("LineEdit_TW3")
        self.verticalLayout_8.addWidget(self.LineEdit_TW3)
        self.LineEdit_TW4 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.LineEdit_TW4.setMaxLength(11)
        self.LineEdit_TW4.setObjectName("LineEdit_TW4")
        self.verticalLayout_8.addWidget(self.LineEdit_TW4)
        self.LineEdit_M = QtWidgets.QLineEdit(self.layoutWidget4)
        self.LineEdit_M.setMaxLength(11)
        self.LineEdit_M.setObjectName("LineEdit_M")
        self.verticalLayout_8.addWidget(self.LineEdit_M)
        self.LineEdit_N = QtWidgets.QLineEdit(self.layoutWidget4)
        self.LineEdit_N.setMaxLength(11)
        self.LineEdit_N.setObjectName("LineEdit_N")
        self.verticalLayout_8.addWidget(self.LineEdit_N)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_8)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 310, 561, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(15, 0, 0, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(Dialog)
        self.tabWidget_TjCalculation.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "PSS参数整定软件"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Dialog", "14"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Dialog", "15"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("Dialog", "16"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("Dialog", "17"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("Dialog", "18"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("Dialog", "19"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("Dialog", "20"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "f"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "AVR"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "PSS"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "SUM"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "AMP"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "ParaName"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "ParaValue"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_AutoCalculateAndPlot.setText(_translate("Dialog", "自动计算相频绘图"))
        self.pushButton_ManualCalculateAndPlot.setText(_translate("Dialog", "手动计算相频绘图"))
        self.pushButton_ReadCSV.setText(_translate("Dialog", "读取CSV"))
        self.pushButton_SaveCSV.setText(_translate("Dialog", "保存CSV"))
        self.pushButton_Reset.setText(_translate("Dialog", "复位"))
        self.radioButton_PSS1.setText(_translate("Dialog", "PSS1"))
        self.radioButton_PSS2A.setText(_translate("Dialog", "PSS2A"))
        self.radioButton_PSS2B.setText(_translate("Dialog", "PSS2B"))
        self.label_29.setText(_translate("Dialog", "高压转子"))
        self.label_30.setText(_translate("Dialog", "中压转子"))
        self.label_31.setText(_translate("Dialog", "低压转子"))
        self.label_32.setText(_translate("Dialog", "发电机"))
        self.LineEdit_GD2_TurbineHighPressureMass.setText(_translate("Dialog", "0"))
        self.LineEdit_GD2_TurbineMiddlePressureMass.setText(_translate("Dialog", "0"))
        self.LineEdit_GD2_TurbineLowPressureMass.setText(_translate("Dialog", "0"))
        self.LineEdit_GD2_GeneratorMass.setText(_translate("Dialog", "189.2"))
        self.label_33.setText(_translate("Dialog", "高压转子"))
        self.label_34.setText(_translate("Dialog", "中压转子"))
        self.label_35.setText(_translate("Dialog", "低压转子"))
        self.label_36.setText(_translate("Dialog", "发电机"))
        self.LineEdit_GR2_TurbineHighPressureMass.setText(_translate("Dialog", "0"))
        self.LineEdit_GR2_TurbineMiddlePressureMass.setText(_translate("Dialog", "0"))
        self.LineEdit_GR2_TurbineLowPressureMass.setText(_translate("Dialog", "0"))
        self.LineEdit_GR2_GeneratorMass.setText(_translate("Dialog", "47.3"))
        self.label_37.setText(_translate("Dialog", "Sn(MVA)"))
        self.label_38.setText(_translate("Dialog", "GD2(t*m2)"))
        self.label_39.setText(_translate("Dialog", "n/min"))
        self.LineEdit_Sn.setText(_translate("Dialog", "667"))
        self.LineEdit_RotorSpeed.setText(_translate("Dialog", "3000"))
        self.LineEdit_GD2.setText(_translate("Dialog", "189.2"))
        self.radioButton_GR2.setText(_translate("Dialog", "GR2（t*m2）"))
        self.radioButton_GD2.setText(_translate("Dialog", "GD2（t*m2）"))
        self.pushButton_TjCalculate.setText(_translate("Dialog", "TJ计算"))
        self.label_28.setText(_translate("Dialog", "TJ"))
        self.LineEdit_Tj.setText(_translate("Dialog", "7"))
        self.tabWidget_TjCalculation.setTabText(self.tabWidget_TjCalculation.indexOf(self.tab), _translate("Dialog", "Tj计算"))
        self.lineEdit_PSSSettingValue.setText(_translate("Dialog", "-90"))
        self.label_11.setText(_translate("Dialog", "PSS补偿角度设定"))
        self.label_12.setText(_translate("Dialog", "-130"))
        self.label_17.setText(_translate("Dialog", "-120"))
        self.label_16.setText(_translate("Dialog", "-110"))
        self.label_15.setText(_translate("Dialog", "-100"))
        self.label_14.setText(_translate("Dialog", "-90"))
        self.label_18.setText(_translate("Dialog", "-80"))
        self.label_40.setText(_translate("Dialog", "-70"))
        self.label_41.setText(_translate("Dialog", "-60"))
        self.tabWidget_TjCalculation.setTabText(self.tabWidget_TjCalculation.indexOf(self.tab_2), _translate("Dialog", "PSS补偿目标角度设定"))
        self.label.setText(_translate("Dialog", "Ks1"))
        self.label_2.setText(_translate("Dialog", "Ks2"))
        self.label_3.setText(_translate("Dialog", "Ks3"))
        self.label_5.setText(_translate("Dialog", "T1"))
        self.label_4.setText(_translate("Dialog", "T2"))
        self.label_6.setText(_translate("Dialog", "T3"))
        self.label_7.setText(_translate("Dialog", "T4"))
        self.label_9.setText(_translate("Dialog", "T5"))
        self.label_8.setText(_translate("Dialog", "T6"))
        self.label_19.setText(_translate("Dialog", "T7"))
        self.label_20.setText(_translate("Dialog", "T8"))
        self.label_21.setText(_translate("Dialog", "T9"))
        self.label_22.setText(_translate("Dialog", "TW1"))
        self.label_23.setText(_translate("Dialog", "TW2"))
        self.label_24.setText(_translate("Dialog", "TW3"))
        self.label_25.setText(_translate("Dialog", "TW4"))
        self.label_26.setText(_translate("Dialog", "M"))
        self.label_27.setText(_translate("Dialog", "N"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

